print("Hello")
print("Hello Again")
print("My name is John Ko")
print("and I am learning")
#print('Python')
#print("the")
print("hard way")
#print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
